ARG YASTACK_BASE_IMAGE=yastack/ubuntu
ARG BASE_VER=18.04


FROM ${YASTACK_BASE_IMAGE}:${BASE_VER}

RUN cd / && git clone https://github.com/saaras-io/yastack.git
RUN cd /yastack/ev/external/protobuf-3.5.0 && ./autogen.sh && ./configure && make && make check && make install && ldconfig
# Do not include tests for packaging
RUN cd /yastack/ev/ && sed -i 's/\(add_subdirectory(test)\)/#\1/' CMakeLists.txt
RUN cd /yastack && mkdir -p build && cd /yastack/build && cmake ..
RUN cd /yastack/build/ && make -s
